<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf8" />
        <title>Distorsion</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,400;0,600;1,400&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="assets/styles/css/style.css" />
    </head>
    <body>
        <?php require "templates/partials/_header.phtml"; ?>
        <?php
            require "templates/$template.phtml";
        ?>
        <script type="module" src="assets/js/main.js"></script>
    </body>
</html>