<html>
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=a-propos">À propos</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
		    if ($route === "home")
		    {
		        require "templates/home.phtml";
		    }
		    else if ($route === "about")
		    {
		        require "templates/about.phtml";
		    }
		    else if ($route === "404")
		    {
		    	require "templates/404.phtml";
		    }
		?>
	</body>
</html>

