<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="Blog">
	<title>Chat Distorsion</title>
	<link rel="stylesheet" href="assets/styles/css/style.css">
</head>
<body>
	<header>
		<a href="index.php"><h1>Distorsion</h1></a>
		<ul>
		  <li><a class="active" href="index.php">Home</a></li>
		  <li><a href="#chat">Chat</a></li>
		</ul>
	</header>		
	
	<main>
		<div class ="left">
			<ol>
				<li>Cinéma 
					<ul>	
						<li>Action</li>
						<li>Comédie</li>
						<li>Science fiction</li>
					</ul>
				</li>
			 
				<li>Littérature
					<ul>
						<li>Roman</li>
						<li>Policier</li>
						<li>Fiction</li>
					</ul>
				</li>
			
				<li>Jeux vidéo
					<ul>
						<li>Mario</li>
						<li>Halo</li>
						<li>God of war</li>
					</ul>
				</li>
				
			</ol>
		</div>
		
		<div class="right">
			<form class="chat-form">
	            <div class="group-inp">
	                <textarea placeholder="Enter your message here" minlength="1" maxlength="1500"></textarea>
	                
	            </div>
					<input type="text" name="Message"/>
	           		<button class="submit" type="submit">Envoyer</button>
	        </div>
	
	    	</form>
	    </div>
	</main>

</body>
</html>
