<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="Blog">
	<title>Chat Distorsion</title>
	<link rel="stylesheet" href="../assets/styles/css/style.css">
</head>
<body>
	<header>
		<img class="salon" src="../assets/img/espace_social.jpg"><a href="index.php"></img></a>
		
		<img class="logo" src="../assets/img/logo (3).jpg"></img>
		
		<ul>
		  <li><a class="active" href="index.php">Home</a></li>
		  <li><a href="#chat">Chat</a></li>
		</ul>
	</header>		
	
	<main>
		<div class ="left">
			<ul>
				<li class="categ" >Cinéma 
					<ul>	
						<li>Action</li>
						<li>Comédie</li>
						<li>Science fiction</li>
					</ul>
				</li>
			 
				<li class="categ" >Littérature
					<ul>
						<li>Roman</li>
						<li>Policier</li>
						<li>Fiction</li>
					</ul>
				</li>
			
				<li class="categ" >Jeux vidéo
					<ul>
						<li>Mario</li>
						<li>Halo</li>
						<li>God of war</li>
					</ul>
				</li>
				
			</ul>
		</div>
		
		<div class ="right">
			<form class ="chat-form">
	            <div class="group-inp">
	                <textarea minlength="1" maxlength="1500"></textarea>
	            </div>
	            <div class ="msg">
					<input placeholder="Enter your message here"  type="text" name="Message"/>
	           		<button class="submit" type="submit">Envoyer</button>
	        	</div>
	
	    	</form>
	    </div>
	</main>
	<footer>
		<p>Copyright Olivier,Kelly,Iman, Jean-louis Corps </p>
	</footer>

</body>
</html>
