<header>
    <h1>Distorsion</h1>
    <nav>
        <ul>
            <?php
            if(!isset($_SESSION["user"]))
            {
            ?>
                <li>
                    <a href="index.php?route=register">Register</a>
                </li>
                <li>
                    <a href="index.php?route=login">Login</a>
                </li>
            <?php
            }
            else
            {
            ?>
                <li>
                    <a href="index.php?route=logout">Logout</a>
                </li>
            <?php
            }
            ?>
        </ul>
    </nav>
</header>